# Generated by Django 5.1.2 on 2024-10-11 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_question_test_alternative_question_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternative',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternatives', to='api.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='tag_type',
            field=models.CharField(choices=[('Números', 'Números'), ('Geometría', 'Geometría'), ('Álgebra y Funciones', 'Álgebra y Funciones'), ('Probabilidad y Estadísticas', 'Probabilidad y Estadísticas')], max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.test'),
        ),
        migrations.CreateModel(
            name='StudentTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('wrong_answers', models.IntegerField(default=0)),
                ('skipped_questions', models.IntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.test')),
            ],
            options={
                'unique_together': {('student', 'test')},
            },
        ),
        migrations.AddField(
            model_name='test',
            name='students',
            field=models.ManyToManyField(through='api.StudentTest', to='api.student'),
        ),
    ]
