# Generated by Django 5.1.2 on 2024-10-11 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_alternative_question_alter_question_tag_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternative',
            name='answer_number',
            field=models.IntegerField(default=1),
        ),
    ]
